version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: klms-postgres
    network_mode: host
    env_file:
      - internal/api/config/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: klms-redis
    network_mode: host
    env_file:
      - internal/api/config/.env
    volumes:
      - redisdata:/data
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: klms-minio
    network_mode: host
    env_file:
      - internal/api/config/.env
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: klms-rabbitmq
    network_mode: host
    env_file:
      - internal/api/config/.env
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    restart: unless-stopped

  klms-server:
    build: .
    image: klms
    container_name: klms-server
    network_mode: host
    env_file:
      - internal/api/config/.env
    depends_on:
      - postgres
      - redis
      - minio
      - rabbitmq
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  miniodata:
  rabbitdata:
